name: Action dos Notes

on:
  workflow_dispatch:

jobs:
  acao_inicial_job:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime Ola
        run: echo "OLÁ"
      - name: Imprime Tchau
        run: echo "TCHAU"
    
